"""Lägg till is_deleted och deleted_at till users

Revision ID: 11638365444e
Revises: 60dabe32bf07
Create Date: 2025-07-11 22:06:33.096998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11638365444e'
down_revision = '60dabe32bf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
