"""Add views to blog_posts and page_views table

Revision ID: 491705b9701d
Revises: b7e27cd05213
Create Date: 2025-07-21 21:28:34.744930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491705b9701d'
down_revision = 'b7e27cd05213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('views')

    op.drop_table('page_views')
    # ### end Alembic commands ###
