"""Lägg till notified till blog_posts_sent

Revision ID: 60dabe32bf07
Revises: 6b795a47e528
Create Date: 2025-07-11 21:38:37.416154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60dabe32bf07'
down_revision = '6b795a47e528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=True))
        batch_op.drop_column('notified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
