"""Rename endpoint to page

Revision ID: c8cfb07814d3
Revises: 99460a94136c
Create Date: 2025-07-22 20:25:12.129771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8cfb07814d3'
down_revision = '99460a94136c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page', sa.String(length=255), nullable=False))
        batch_op.alter_column('views',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_index('endpoint')
        batch_op.create_unique_constraint(None, ['page'])
        batch_op.drop_column('endpoint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('endpoint', ['endpoint'], unique=True)
        batch_op.alter_column('views',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('page')

    # ### end Alembic commands ###
