"""Lägg till email_sent till blog_posts

Revision ID: ffc2c1ef7725
Revises: d2900c7e6677
Create Date: 2025-07-11 20:39:41.862699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc2c1ef7725'
down_revision = 'd2900c7e6677'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'email_sent',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
