"""Add daily stats table

Revision ID: fff6419dcbcd
Revises: 02001f66f53b
Create Date: 2026-03-25 16:55:51.030722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff6419dcbcd'
down_revision = '02001f66f53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'page', name='_date_page_uc')
    )
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_stats_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_stats_date'))

    op.drop_table('daily_stats')
    # ### end Alembic commands ###
